name: aqi_predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - pyarrow
  - requests
  - tqdm
  - joblib
  - mlflow
  - shap
  - fastapi
  - uvicorn
  - streamlit
  - jupyter
  - notebook
  - plotly
  - ipywidgets
  - pip:
      - python-dotenv
      - openmeteo-requests
      - openai
      - streamlit-option-menu
      - aiohttp
